spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/student_management
# config logging
logging:
  file:
    name: logs/applications.log
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: INFO
      springframework:
        web: DEBUG
    com:
      example:
        student_management: TRACE
# set static variable value
student_management:
  auth:
    jwt:
      JWT_SECRET: itachi
      JWT_EXPIRATION: 86400000 # expire in one day (unit: ms)